# Generated by Django 5.0.14 on 2025-06-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TblRecordSlip',
        ),
    ]
