# Generated by Django 5.0.14 on 2025-06-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0002_delete_tblrecordslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblRecordSlip',
            fields=[
                ('invoiceid', models.AutoField(db_column='invoiceID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=100)),
                ('language_from', models.CharField(max_length=50)),
                ('language_to', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('interpretation_hours', models.IntegerField()),
                ('total_interpretation', models.IntegerField()),
                ('proof_read_words', models.IntegerField()),
                ('proof_read_total', models.IntegerField()),
                ('translated_words', models.IntegerField()),
                ('translated_total', models.IntegerField()),
                ('transcription_hours', models.IntegerField()),
                ('transcription_total', models.IntegerField()),
                ('forty_translation', models.IntegerField()),
                ('forty_proof_reading', models.IntegerField()),
                ('forty_interpretation', models.IntegerField()),
                ('forty_transcription', models.IntegerField()),
                ('sixty_translation', models.IntegerField()),
                ('sixty_proof_reading', models.IntegerField()),
                ('sixty_interpretation', models.IntegerField()),
                ('sixty_transcription', models.IntegerField()),
                ('stamp_seal_translation', models.IntegerField()),
                ('stamp_seal_proof_reading', models.IntegerField()),
                ('sub_total_translation', models.IntegerField()),
                ('sub_total_proof_reading', models.IntegerField()),
                ('sub_total_interpretation', models.IntegerField()),
                ('sub_total_transcription', models.IntegerField()),
                ('total_forty_percent', models.IntegerField()),
                ('total_sixty_percent', models.IntegerField()),
                ('level_of_education', models.CharField(max_length=100)),
                ('tuition_amount', models.CharField(max_length=100)),
                ('tuition_hours', models.CharField(max_length=100)),
                ('tuition_total_paid', models.CharField(max_length=100)),
                ('software_service_total', models.CharField(max_length=100)),
                ('ies_total', models.CharField(max_length=100)),
                ('grand_total_ksh', models.IntegerField()),
                ('month', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=10)),
                ('service_payment_status', models.CharField(max_length=10)),
                ('slip_no', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tbl_record_slip',
                'managed': False,
            },
        ),
    ]
