# Generated by Django 5.0.14 on 2025-06-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0003_tblrecordslip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('semester', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.CharField(blank=True, max_length=250, null=True)),
                ('course_title', models.CharField(blank=True, max_length=250, null=True)),
                ('credit', models.CharField(blank=True, max_length=250, null=True)),
                ('school', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
