# Generated by Django 5.0.14 on 2025-06-25 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0004_courselists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselists',
            old_name='course',
            new_name='course_code',
        ),
    ]
