# Generated by Django 5.0.14 on 2025-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0005_rename_course_courselists_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblClaimSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('normal_class', models.CharField(max_length=100)),
                ('normal_time', models.CharField(max_length=100)),
                ('normal_mark', models.CharField(max_length=100)),
                ('normal_number', models.CharField(max_length=100)),
                ('special_class', models.CharField(max_length=100)),
                ('special_time', models.CharField(max_length=100)),
                ('special_mark', models.CharField(max_length=100)),
                ('special_number', models.CharField(max_length=100)),
                ('onsite_class', models.CharField(max_length=100)),
                ('onsite_time', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_claim_sheet',
                'managed': False,
            },
        ),
    ]
