# Generated by Django 5.0.14 on 2025-06-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0006_tblclaimsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='class_no',
            new_name='Year',
        ),
    ]
