# Generated by Django 5.0.14 on 2025-06-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0007_rename_class_no_timetable_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='Year',
            new_name='year',
        ),
    ]
