# Generated by Django 5.0.14 on 2025-06-27 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0008_rename_year_timetable_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('month', models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('APRIL', 'April'), ('MAY', 'May'), ('JUNE', 'June'), ('JULLY', 'Jully'), ('AUGUST', 'August'), ('SEPTEMBER', 'September'), ('OCTOBER', 'October'), ('NOVEMBER', 'November'), ('DECEMBER', 'December')], max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('hours', 'Hours'), ('meetings', 'Meetings'), ('invigilation_core', 'Invigilation - Core Course'), ('invigilation_elective', 'Invigilation - Elective Course'), ('marking_cat', 'Marking of CATs'), ('marking_exam', 'Marking of Final Exams')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimitems', to='staff_teachers.claimform')),
            ],
        ),
    ]
