# Generated by Django 5.0.14 on 2025-06-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0009_claimform_claimitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='staff_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='claimform',
            name='staff_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
