# Generated by Django 5.0.14 on 2025-06-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0010_claimform_staff_email_alter_claimform_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
