# Generated by Django 5.0.14 on 2025-06-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0011_claimform_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimform',
            name='state',
            field=models.CharField(blank=True, choices=[('Registrar Approval', 'Registrar Approval'), ('Dean Approval', 'Dean Approval')], max_length=250, null=True),
        ),
    ]
