# Generated by Django 5.0.14 on 2025-06-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0012_claimform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimform',
            name='state',
            field=models.CharField(blank=True, choices=[('Registrar Approval', 'Registrar Approval'), ('Dean Approval', 'Dean Approval'), ('Payment', 'Payment')], max_length=250, null=True),
        ),
    ]
