# Generated by Django 5.0.14 on 2025-07-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0013_alter_claimform_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('class_level', models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3')])),
                ('time_slot', models.CharField(choices=[('08:30-09:20', '08:30–09:20'), ('09:25-10:15', '09:25–10:15'), ('10:30-11:20', '10:30–11:20'), ('11:25-12:15', '11:25–12:15'), ('14:30-15:30', '14:30–15:30'), ('15:30-16:30', '15:30–16:30')], max_length=20)),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.TextField()),
                ('lecturer', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='claimform',
            name='state',
            field=models.CharField(blank=True, choices=[('Registrar Approval', 'Registrar Approval'), ('Dean Approval', 'Dean Approval'), ('Payment', 'Payment'), ('Paid', 'Paid')], max_length=250, null=True),
        ),
    ]
