# Generated by Django 5.0.14 on 2025-07-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0014_timetableentry_alter_claimform_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableEntry',
        ),
    ]
