# Generated by Django 5.0.14 on 2025-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0015_delete_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('class_level', models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3')])),
                ('course_code_first', models.CharField(max_length=100)),
                ('course_title_first', models.TextField()),
                ('lecturer_first', models.CharField(max_length=100)),
                ('course_code_second', models.CharField(max_length=100)),
                ('course_title_second', models.TextField()),
                ('lecturer_second', models.CharField(max_length=100)),
                ('course_code_third', models.CharField(max_length=100)),
                ('course_title_third', models.TextField()),
                ('lecturer_third', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
    ]
