# Generated by Django 5.0.14 on 2025-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0016_timetableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='lecturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
