# Generated by Django 5.0.14 on 2025-07-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0017_timetableentry_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_code_third',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_title_third',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='lecturer_third',
        ),
    ]
