# Generated by Django 5.0.14 on 2025-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0018_remove_timetableentry_course_code_third_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='time_slot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
