# Generated by Django 5.0.14 on 2025-07-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0019_timetableentry_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_course_code_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_course_code_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_course_title_first',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_course_title_second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_lecturer_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_lecturer_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_break_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_course_code_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_course_code_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_course_title_first',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_course_title_second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_lecturer_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_lecturer_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='course_code_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='course_code_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='course_title_second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lecturer_first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lecturer_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
