# Generated by Django 5.0.14 on 2025-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0020_timetableentry_after_break_course_code_first_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetableentry',
            old_name='after_break_room',
            new_name='after_break_first_room',
        ),
        migrations.RenameField(
            model_name='timetableentry',
            old_name='after_lunch_room',
            new_name='after_break_second_room',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_first_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='after_lunch_second_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='first_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='second_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
