# Generated by Django 5.0.14 on 2025-07-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0021_rename_after_break_room_timetableentry_after_break_first_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='class_level',
            field=models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3')], max_length=10),
        ),
    ]
