# Generated by Django 5.0.14 on 2025-07-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0022_alter_timetableentry_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='class_level',
            field=models.IntegerField(choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3')]),
        ),
    ]
