# Generated by Django 5.0.14 on 2025-07-08 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0023_alter_timetableentry_class_level'),
        ('student', '0015_alter_tblstudentsadmissions_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('letter_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
            ],
            options={
                'unique_together': {('academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_teachers.course')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_teachers.academicperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.tblstudentsadmissions')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accumulated_credits', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_awarded', models.CharField(blank=True, max_length=50, null=True)),
                ('award_date', models.DateField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.tblstudentsadmissions')),
            ],
        ),
    ]
