# Generated by Django 5.0.14 on 2025-07-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0024_gradescale_course_code_course_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_teachers.courselists'),
        ),
    ]
