# Generated by Django 5.0.14 on 2025-07-08 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0025_alter_transcriptentry_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptentry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_teachers.course'),
        ),
    ]
