# Generated by Django 5.0.14 on 2025-07-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0027_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimform',
            name='state',
            field=models.CharField(blank=True, choices=[('Registrar Approval', 'Registrar Approval'), ('DVC Finance Approval', 'DVC Finance Approval'), ('Payment', 'Payment'), ('Paid', 'Paid')], max_length=250, null=True),
        ),
    ]
