# Generated by Django 5.0.14 on 2025-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0028_alter_claimform_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='max_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='min_score',
            field=models.PositiveIntegerField(),
        ),
    ]
