# Generated by Django 5.0.14 on 2025-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0029_alter_gradescale_max_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperiod',
            name='academic_year',
            field=models.CharField(choices=[('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], max_length=9),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], max_length=100),
        ),
    ]
