# Generated by Django 5.0.14 on 2025-07-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0031_alter_transcriptentry_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='philosophystudentsresults',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff_teachers.academicperiod'),
            preserve_default=False,
        ),
    ]
