# Generated by Django 5.0.14 on 2025-07-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0032_philosophystudentsresults_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='philosophystudentsresults',
            name='period',
        ),
    ]
