# Generated by Django 5.2.4 on 2025-07-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0033_remove_philosophystudentsresults_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academicperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transcriptentry',
            name='period',
        ),
        migrations.RemoveField(
            model_name='philosophystudentsresults',
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseLists',
        ),
        migrations.DeleteModel(
            name='GradeScale',
        ),
        migrations.RemoveField(
            model_name='philosophystudentsresults',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transcriptentry',
            name='course',
        ),
        migrations.RemoveField(
            model_name='transcriptentry',
            name='student',
        ),
        migrations.RemoveField(
            model_name='transcriptsummary',
            name='student',
        ),
        migrations.DeleteModel(
            name='AcademicPeriod',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='PhilosophystudentsResults',
        ),
        migrations.DeleteModel(
            name='TranscriptEntry',
        ),
        migrations.DeleteModel(
            name='TranscriptSummary',
        ),
    ]
