# Generated by Django 5.2.4 on 2025-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0034_alter_academicperiod_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentsResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.CharField(blank=True, max_length=200, null=True)),
                ('s_no', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('plato_republic', models.CharField(blank=True, max_length=200, null=True)),
                ('modern_world_history', models.CharField(blank=True, max_length=200, null=True)),
                ('special_ethicks', models.CharField(blank=True, max_length=200, null=True)),
                ('logic', models.CharField(blank=True, max_length=200, null=True)),
                ('emmanuel_kant', models.CharField(blank=True, max_length=200, null=True)),
                ('edith_stein', models.CharField(blank=True, max_length=200, null=True)),
                ('philosophical_latin', models.CharField(blank=True, max_length=200, null=True)),
                ('christianity_philosophy', models.CharField(blank=True, max_length=200, null=True)),
                ('ancient_thought', models.CharField(blank=True, max_length=200, null=True)),
                ('comprehensive_written', models.CharField(blank=True, max_length=200, null=True)),
                ('comprehensives_oral', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
