# Generated by Django 5.2.4 on 2025-07-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0035_studentsresults'),
        ('student', '0024_delete_courseresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('year', models.CharField(choices=[('2020-21', '2020-21'), ('2021-22', '2021-22'), ('2022-23', '2022-23'), ('2023-24', '2023-24'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28'), ('2028-29', '2028-29'), ('2029-30', '2029-30')], default='2023-24', max_length=10)),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], default='Semester 1', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation', models.CharField(blank=True, max_length=250, null=True)),
                ('course_code', models.CharField(blank=True, max_length=100, null=True)),
                ('course_title', models.CharField(blank=True, max_length=250, null=True)),
                ('semester', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2025, max_length=4)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='student.tblstudentsadmissions')),
            ],
            options={
                'db_table': 'tbl_results',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='studentsResults',
        ),
    ]
