# Generated by Django 5.2.4 on 2025-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0036_course_courseresults_delete_studentsresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresults',
            name='year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], default='Year 1', max_length=250),
        ),
    ]
