# Generated by Django 5.2.4 on 2025-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0037_alter_courseresults_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresults',
            name='year',
            field=models.CharField(choices=[('2024-25', '2024-25'), ('2025-26', '2025-26'), ('2026-27', '2026-27'), ('2027-28', '2027-28')], default='2024-25', max_length=250),
        ),
    ]
