# Generated by Django 5.2.4 on 2025-07-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0038_alter_courseresults_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresults',
            name='class_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
