# Generated by Django 5.0.14 on 2025-08-13 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0039_courseresults_class_no'),
        ('student', '0025_alter_courselists_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresults',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='student.tblstudentsadmissions'),
        ),
    ]
