# Generated by Django 5.0.14 on 2025-10-28 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0040_alter_courseresults_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('payment_code', models.CharField(max_length=50)),
                ('adm', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tbl_psychology_registration',
                'managed': True,
            },
        ),
    ]
