# Generated by Django 5.0.14 on 2025-10-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_teachers', '0041_psychologyregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologyregistration',
            name='payment_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
