"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vvccg6^@(asd7g(kwtw298^7@f0p09n^)o3eji)%!#&$c8te#a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["ciu.ac.ke", "www.ciu.ac.ke", "127.0.0.1", "localhost"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userauth',
    'student',
    'staff_teachers',
    'consolata_admin',
    'widget_tweaks',
    'home',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases




# Production DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'otijeuil_consolata_local',
        'USER': 'otijeuil_admin',
        'PASSWORD': 'WTL_T3p=jcEAPnjQ',
        'HOST': '102.212.247.162',
        'PORT': '',
    },
    'old_website':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'otijeuil_cipkenya_cip_website',
        'USER': 'otijeuil_admin',
        'PASSWORD': 'WTL_T3p=jcEAPnjQ',
        'HOST': '102.212.247.162',
        'PORT': '',
    }
        
}


# Local DB
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'consolata_local',
#         'USER': 'dommy',
#         'PASSWORD': 'dommy123',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     },
#     'old_website':{
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'otijeuil_cipkenya_cip_website',
#         'USER': 'dommy',
#         'PASSWORD': 'dommy123',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
        
# }





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'userauth.CustomUser'
AUTHENTICATION_BACKENDS = ['userauth.backends.EmailBackend',
                            'django.contrib.auth.backends.ModelBackend',]
# For testing: Emails print to console
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# for production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'system@ciu.ac.ke'
EMAIL_HOST_PASSWORD = 'os0GbOm!ycf0Djny'



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Production
STATIC_URL = '/consolata/static/'  # because your app runs under /consolata/
STATIC_ROOT = Path('/home/otijeuil/public_html/consolata/static/')  # adjust to your cPanel user
STATICFILES_DIRS = [BASE_DIR / 'static']

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

#Local
# STATIC_URL = '/static/'

# Where collectstatic will copy files for production
# STATIC_ROOT = BASE_DIR / 'staticfiles'  

# Where your custom static assets live during dev
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
LOGIN_URL = 'userauth:login'  # Or the name/path of your login view
# LOGIN_REDIRECT_URL = 'userauth:profile'  # Redirect after login
LOGOUT_REDIRECT_URL = 'home:home'  # Redirect after logout
SESSION_COOKIE_AGE = 1209600  # Two weeks in seconds

