# Generated by Django 5.0.14 on 2025-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_reg_no_studentclasssignin_reg_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblstudentsadmissions',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
