# Generated by Django 5.0.14 on 2025-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_tblstudentsadmissions_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
