# Generated by Django 5.2.4 on 2025-07-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_rename_results_courseresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_title', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'tbl_course_codes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('corse_title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_course_lists',
                'managed': True,
            },
        ),
    ]
