# Generated by Django 5.2.4 on 2025-07-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_coursecodes_courselists'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselists',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
