# Generated by Django 5.2.4 on 2025-07-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_courselists_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselists',
            name='credit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
