# Generated by Django 5.2.4 on 2025-07-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_courselists_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselists',
            old_name='corse_title',
            new_name='course_title',
        ),
    ]
