# Generated by Django 5.2.4 on 2025-07-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_rename_corse_title_courselists_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselists',
            name='course_code',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='courselists',
            name='course_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='courselists',
            name='semester',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='courselists',
            name='year',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
