# Generated by Django 5.2.4 on 2025-07-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_alter_courselists_course_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseResults',
        ),
    ]
