# Generated by Django 5.2.4 on 2025-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_delete_courseresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselists',
            name='credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
