# Generated by Django 5.0.14 on 2025-08-13 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_courselists_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseLists',
        ),
    ]
