# Generated by Django 5.0.14 on 2025-08-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_delete_courselists'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=250, unique=True)),
                ('course_title', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('semester', models.CharField(blank=True, max_length=250, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_course_lists',
                'managed': True,
            },
        ),
    ]
