# Generated by Django 5.0.14 on 2025-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_courselists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='admission_year',
            field=models.CharField(blank=True, default=2025, max_length=20, null=True),
        ),
    ]
