# Generated by Django 5.0.14 on 2025-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_alter_tblstudentsadmissions_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('citizenship', models.CharField(max_length=100)),
                ('passport_or_id_no', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10)),
                ('religious_affiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('religious_status', models.CharField(blank=True, choices=[('priest', 'Priest'), ('deacon', 'Deacon'), ('sister', 'Sister'), ('brother', 'Brother'), ('seminarian', 'Seminarian'), ('none', 'Not Religious')], max_length=20, null=True)),
                ('diocese', models.CharField(blank=True, max_length=150, null=True)),
                ('congregation', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('next_of_kin_address', models.TextField(blank=True, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('study_mode', models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('auditing', 'Auditing'), ('evening', 'Evening Study'), ('weekend', 'Weekend'), ('distance', 'Distance Learning')], max_length=20)),
                ('school_applied', models.CharField(max_length=150)),
                ('programme_applied', models.CharField(max_length=150)),
                ('anticipated_duration_years', models.IntegerField(choices=[(1, '1 years'), (2, '2 years'), (3, '3 years'), (4, '4 years')])),
                ('studied_before', models.BooleanField(default=False)),
                ('previous_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=150, null=True)),
                ('enrollment_from', models.IntegerField(blank=True, null=True)),
                ('enrollment_to', models.IntegerField(blank=True, null=True)),
                ('universities_attended', models.TextField(blank=True, null=True)),
                ('high_school_attended', models.TextField(blank=True, null=True)),
                ('recommending_authority', models.CharField(blank=True, max_length=150, null=True)),
                ('recommending_organization', models.CharField(blank=True, max_length=150, null=True)),
                ('recommendation_address', models.TextField(blank=True, null=True)),
                ('recommendation_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('recommendation_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sponsor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('sponsor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_address', models.TextField(blank=True, null=True)),
                ('sponsor_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sponsor_province', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=200, null=True)),
                ('has_disability', models.BooleanField(default=False)),
                ('nature_of_disability', models.TextField(blank=True, null=True)),
                ('consent_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tblstudentsadmissions',
            name='duration',
            field=models.CharField(choices=[('1 Months', '1 Months'), ('2 Months', '2 Months'), ('3 Months', '3 Months'), ('4 Months', '4 Months'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3 Year', '3 Year'), ('4 Year', '4 Year')], max_length=20),
        ),
    ]
