# Generated by Django 5.0.14 on 2025-10-09 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_studentapplication_applicant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='high_school_attended',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='universities_attended',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time'), ('auditing', 'Auditing'), ('evening', 'Evening Study'), ('weekend', 'Weekend'), ('distance', 'Distance Learning')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('college', 'College'), ('seminary', 'Seminary'), ('university', 'University'), ('other', 'Other')], max_length=20)),
                ('institution_name', models.CharField(max_length=255)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_or_result', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_rows', to='student.studentapplication')),
            ],
            options={
                'ordering': ['-to_year', 'institution_type'],
            },
        ),
    ]
