# Generated by Django 5.0.14 on 2025-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_remove_studentapplication_high_school_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='anticipated_duration_years',
            field=models.IntegerField(blank=True, choices=[('1 year', '1 Year'), ('2 years', '2 Years'), ('3 years', '3 Years'), ('4 years', '4 Years')], null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='programme_applied',
            field=models.CharField(blank=True, choices=[('baccalaureate', 'Baccalaureate'), ('bachelor', 'Bachelor'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='school_applied',
            field=models.CharField(blank=True, choices=[('school of Philosophy', 'School Of Philosophy'), ('school of theology', 'School Of Theology'), ('school of counselling psychology', 'School Of Counselling Psychology')], max_length=150, null=True),
        ),
    ]
