# Generated by Django 5.0.14 on 2025-10-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_alter_studentapplication_anticipated_duration_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='anticipated_duration_years',
            field=models.CharField(blank=True, choices=[('1 year', '1 Year'), ('2 years', '2 Years'), ('3 years', '3 Years'), ('4 years', '4 Years')], max_length=150, null=True),
        ),
    ]
