# Generated by Django 5.0.14 on 2025-10-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_studentapplication_anticipated_duration_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='application_fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='applications/fees/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='cv_resume',
            field=models.FileField(blank=True, null=True, upload_to='applications/cv/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='degree_certificates',
            field=models.FileField(blank=True, null=True, upload_to='applications/degrees/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='higher_diplomas',
            field=models.FileField(blank=True, null=True, upload_to='applications/diplomas/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='highschool_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/highschool/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='letter_of_interest_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/interest/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='letter_of_interest_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='applications/passports/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='passport_photos',
            field=models.FileField(blank=True, null=True, upload_to='applications/photos/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='professional_certificates',
            field=models.FileField(blank=True, null=True, upload_to='applications/professional/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='recommendation_letters',
            field=models.FileField(blank=True, null=True, upload_to='applications/recommendations/'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='transcripts',
            field=models.FileField(blank=True, null=True, upload_to='applications/transcripts/'),
        ),
    ]
