# Generated by Django 5.0.14 on 2025-10-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_studentapplication_application_fee_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='application_fee_receipt',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='cv_resume',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='degree_certificates',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='higher_diplomas',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='highschool_certificate',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='letter_of_interest_file',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='letter_of_interest_text',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='passport_copy',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='passport_photos',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='professional_certificates',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='recommendation_letters',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='transcripts',
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/documents/%Y/%m/%d/')),
                ('attachment_type', models.CharField(choices=[('fee_receipt', 'Application Fee Receipt'), ('id_passport', 'ID / Passport'), ('passport_photo', 'Passport Photo'), ('degree', 'Degree Certificate'), ('transcript', 'Transcript'), ('professional', 'Professional Qualification'), ('diploma', 'Diploma / Certificate'), ('highschool', 'High School Certificate'), ('cv', 'Curriculum Vitae'), ('recommendation', 'Recommendation Letter'), ('letter_of_interest', 'Letter of Interest File'), ('other', 'Other')], default='other', max_length=40)),
                ('original_filename', models.CharField(blank=True, max_length=512, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='student.studentapplication')),
            ],
        ),
    ]
