# Generated by Django 5.0.14 on 2025-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, choices=[('Degree', 'Degree'), ('Masters', 'Masters'), ('Doctor', 'Doctor'), ('Professor', 'Professor')], max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
