# Generated by Django 5.0.14 on 2025-11-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_qualification_customuser_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rates',
            field=models.IntegerField(default=0),
        ),
    ]
