# Generated by Django 5.0.14 on 2025-07-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Formator', 'Formator'), ('Registrar', 'Registrar'), ('DVC Finance', 'DVC Finance'), ('Finance Controller', 'Finance Controller'), ('Secretary', 'Secretary')], max_length=20),
        ),
    ]
