# Generated by Django 5.2.4 on 2025-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Formator', 'Formator'), ('Registrar', 'Registrar'), ('DVC Finance', 'DVC Finance'), ('Finance Administrator', 'Finance Administrator'), ('Secretary', 'Secretary'), ('The Rector', 'The Rector'), ('DVC Academics', 'DVC Academics'), ('HOD Language', 'HOD Language'), ('IT Administrator', 'IT Administrator')], max_length=200),
        ),
    ]
