# Generated by Django 5.0.14 on 2025-08-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Lecturer', 'Lecturer'), ('Formator', 'Formator'), ('Registrar', 'Registrar'), ('DVC Finance', 'DVC Finance'), ('Finance Administrator', 'Finance Administrator'), ('Secretary', 'Secretary'), ('The Rector', 'The Rector'), ('DVC Academics', 'DVC Academics'), ('HOD Language', 'HOD Language'), ('IT Administrator', 'IT Administrator')], max_length=300),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.CharField(blank=True, choices=[('Philosophy', 'Philosophy'), ('Language', 'Language'), ('Psychology', 'Psychology'), ('Theology', 'Theology')], max_length=20),
        ),
    ]
